name: Build Android

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - "include/**"
      - "src/**"
      - "CMakeLists.txt"
      - "cmake/**"
      - "module/**"
      - "shaders/**"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - "include/**"
      - "src/**"
      - "CMakeLists.txt"
      - "cmake/**"
      - "module/**"
      - "shaders/**"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache (NDK)
        uses: actions/cache@v2
        with:
          path: ${ANDROID_HOME}/ndk/21.3.6528147
          key: ndk-cache

      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install 'ndk;21.3.6528147'

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_EXAMPLE=OFF -DBUILD_TEST=OFF -DVULKAN_BACKEND=ON -DCMAKE_TOOLCHAIN_FILE=${ANDROID_HOME}/ndk/21.3.6528147/build/cmake/android.toolchain.cmake -DANDROID_ABR=arm64-v8a -DANDROID_PLATFORM=android-29 -DANDROID_STL=c++_shared -DCMAKE_SYSTEM_NAME=Android

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
